### ISSUE TITLE
Try to use prismarine-block, prismarine-item (and maybe prismarine-entity)

### ISSUE THREAD

**Issue by rom1504** [1b8/schematic#1]
The purpose of these prismarine-\* libs is to put things in common between different js+minecraft project. Currently mineflayer and flying-squid use them. 

It would be nice to try to use them here too so other projects can use this lib easily.

That would probably require some changes in these prismarine- libs, but that's okay, if we can find a common ground providing more features for everybody, that's better.

(of course that could happen later once you know more about what you need and all)

In practice for example, you could have a function that takes a raw item and return a prismarine-item (for this https://github.com/1b8/schematic/blob/master/lib/item.js), it seems like prismarine-item constructor would fit (https://github.com/PrismarineJS/prismarine-item#itemtype-count-metadata-nbt)

**Comment by 1b8** [comment]
I did originally use those libs, but switched because they didn't have as many features. I'll switch back.

**Comment by 1b8** [comment]
Now uses prismarine-block and -item; although I used an object (from prismarine-nbt) instead of a Buffer for `item.nbt`. Since it's already been parsed, why turn it back into a buffer?

**Comment by rom1504** [comment]
Ah, nice! No keep the prismarine-nbt object in item.nbt, that default (https://github.com/PrismarineJS/prismarine-item/blob/master/index.js#L19) come from a time where we didn't parse the nbt, it should be changed now.
