### ISSUE TITLE
Examples not working on Master or Dev

### ISSUE THREAD

**Issue by bluetidepro** [1b8/schematic#4]
Am I doing something wrong here? I've tried to run the examples, but can't seem to get it to work. Even on the dev branch.

Could you possible provide more details on how you get this to run? It could be my node version or something. You may want to consider adding something like this to your package file:

```
...
  "engines": {
    "node": "0.12.7",
    "npm": "2.11.4"
  },
...
```

So, I (the user) know what version you are running for npm/node on your repo.

But yeah, any help would be really incredible to get this to run. Thanks so much!

**Comment by rom1504** [comment]
examples work in #3

**Comment by bluetidepro** [comment]
@rom1504 I tried in your PR/branch even, and they don't work. What version of npm and node are you running? For me, It's:

```
> npm -v
> 2.5.1

> node -v
> v0.12.9
```

**Comment by rom1504** [comment]
What do you mean by "they don't work" ? Do you get an error ?
I'm using node5 but it should work with 0.12 I think

**Comment by bluetidepro** [comment]
@rom1504 I pulled your fixes branch, ran `npm install

**Comment by bluetidepro** [comment]
@rom1504 I pulled your fixes branch, ran `npm install`, then `cd doc`, then `node examples.js` to run the test, and I get this error: 

```
schematic-fixes/node_modules/prismarine-nbt/nbt.js:43
      return Object.keys(value).reduce((acc,key) => {
                                                 ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (schematic-fixes/index.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Isn't that the correct way to run the test? Or did I do something wrong?

**Comment by 1b8** [comment]
It looks like your Node version doesn't support ES6 function arrows...

**Comment by bluetidepro** [comment]
@1b8 So it IS my node version? What's the version you both are running (cc: @rom1504)? Also, were my steps above at least the correct way run the test example?

**Comment by 1b8** [comment]
In rom1504's fixes branch, he updated prismarine-nbt. The new version uses ES6 function arrows. I am currently using Node `v4.1.1`, and function arrows work. Try upating.

The test files in the current `master` and `dev` branches have to be copied into a folder that has  `mc-schematic` as a module.

**Comment by bluetidepro** [comment]
@1b8 @rom1504 Nice, that did it. Again I'd reccomend added that `"engines"` object to the package file so people can see what versions of stuff you are running just in case they get errors like that.

**Comment by 1b8** [comment]
Added `engines` field and published to npm. It's actually prismarine-nbt that caused the error.

Hmm... maybe I should have added `engines` once rom1504's `fixes` was merged...

**Comment by 1b8** [comment]
Actually, if anything should have the `engines` field, it would be prismarine-nbt...
Reverted adding `engines` field and published to npm.

**Comment by rom1504** [comment]
@1b8 yeah I'll do that (or simply not use arrow functions there idk I'll see)
